version: "2"

services:
  cockpit-example-php:
    image: wodby/php:7.1
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - cockpit-example-sync:/var/www/html:nocopy

  cockpit-example-nginx:
    image: wodby/php-nginx:1.13
    depends_on:
      - cockpit-example-php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: error
      NGINX_BACKEND_HOST: cockpit-example-php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - cockpit-example-sync:/var/www/html:nocopy
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:cockpit-example.docker.localhost'

  cockpit-example-mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.cockpit-example.docker.localhost'

  cockpit-example-traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  cockpit-example-sync:
    external: true
